name: Simple CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  detect-affected-services:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.set-affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Detect affected services
        id: set-affected
        run: |
          echo "Detecting changed services..."
          # Get changed files between HEAD and base (for PRs) or last commit (for push)
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            git fetch origin ${{ github.base_ref }}
            CHANGED=$(git diff --name-only origin/${{ github.base_ref }})
          else
            CHANGED=$(git diff --name-only HEAD~1)
          fi
          echo "Changed files: $CHANGED"
          
          # Extract unique service directories
          SERVICES=""
          for file in $CHANGED; do
            if [[ $file == services/*/* ]]; then
              service=$(echo $file | cut -d'/' -f2)
              SERVICES+="$service "
            fi
          done
          
          # Remove duplicates and handle empty case
          SERVICES=$(echo $SERVICES | tr ' ' '\n' | sort -u | tr '\n' ' ')
          SERVICES=$(echo $SERVICES | xargs) # trim
          
          if [ -z "$SERVICES" ]; then
            echo "No services were affected"
            echo "affected=[]" >> $GITHUB_OUTPUT
          else
            echo "Affected services: $SERVICES"
            # Format as proper JSON array with quotes
            SERVICES_JSON="[\"$(echo $SERVICES | sed 's/ /","/g')\"]"
            echo "affected=$SERVICES_JSON" >> $GITHUB_OUTPUT
          fi

  build:
    needs: detect-affected-services
    runs-on: ubuntu-latest
    if: needs.detect-affected-services.outputs.affected != '[]'
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-affected-services.outputs.affected) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build affected service
        run: |
          cd services/${{ matrix.service }}
          go build -v .
